server:
  port: 9001
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhxy_db?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    username: root
    password: 123456
    #username: shangguigu
    #mybatis-plus\u5185\u7F6E\u8FDE\u63A5\u6C60
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  thymeleaf:
    #\u6A21\u677F\u7684\u6A21\u5F0F\uFF0C\u652F\u6301 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #\u7F16\u7801 \u53EF\u4E0D\u7528\u914D\u7F6E
    encoding: UTF-8
    #\u5F00\u53D1\u914D\u7F6E\u4E3Afalse,\u907F\u514D\u4FEE\u6539\u6A21\u677F\u8FD8\u8981\u91CD\u542F\u670D\u52A1\u5668
    cache: false
    #\u914D\u7F6E\u6A21\u677F\u8DEF\u5F84\uFF0C\u9ED8\u8BA4\u662Ftemplates\uFF0C\u53EF\u4EE5\u4E0D\u7528\u914D\u7F6E
    prefix: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    #\u8BBE\u7F6E\u6587\u4EF6\u4E0A\u4F20\u4E0A\u9650
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    #\u6DFB\u52A0\u65E5\u5FD7\u652F\u6301
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
